import{A as b,a as w,b as h,c as y}from"./assets/vendor-YScXsqbV.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))c(o);new MutationObserver(o=>{for(const s of o)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&c(l)}).observe(document,{childList:!0,subtree:!0});function n(o){const s={};return o.integrity&&(s.integrity=o.integrity),o.referrerPolicy&&(s.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?s.credentials="include":o.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function c(o){if(o.ep)return;o.ep=!0;const s=n(o);fetch(o.href,s)}})();const m=new b(".about-me__accord_list",{duration:350,elementClass:"about-me__accord_item",triggerClass:"about-me__accord_trigger",panelClass:"about-me__accord_panel",showMultiple:!0,onOpen:_});m.detachEvents();m.open(0);setTimeout(()=>{m.attachEvents()},1e3);function _(t){const e=t.getBoundingClientRect(),n=Math.max(document.documentElement.clientHeight,window.innerHeight);e.bottom>n&&window.scrollTo({top:e.top+window.scrollY-(n-e.height)/2,behavior:"smooth"})}new b(".faq-accordion-container",{duration:350,showMultiple:!0,onOpen:L});function L(t){const e=t.getBoundingClientRect(),n=Math.max(document.documentElement.clientHeight,window.innerHeight);e.bottom>n&&window.scrollTo({top:e.top+window.scrollY-(n-e.height)/2,behavior:"smooth"})}const a=document.querySelector("#covers"),d=a.querySelector(".top-line"),u=a.querySelector(".mid-line"),p=a.querySelector(".bottom-line"),f=a.querySelector(".additional-line"),E={rootMargin:"0px",threshold:0},O=t=>{t.forEach(e=>{e.isIntersecting?(d.classList.add("animation"),u.classList.add("animation-reverse"),p.classList.add("animation"),f.classList.add("animation-reverse")):(d.classList.remove("animation"),u.classList.remove("animation-reverse"),p.classList.remove("animation"),f.classList.remove("animation-reverse"))})},S=new IntersectionObserver(O,E);S.observe(a);const C="/project-team-10/assets/icon-BTOTQ9Pm.svg",r={client_email:"",client_comment:""},i=document.querySelector(".wt-form");w.defaults.baseURL="https://portfolio-js.b.goit.study/api";const q=async t=>{const e={email:t.client_email,comment:t.client_comment};return await w.post("/requests",e)},I=t=>y.create(`
    <div class="wt-modal-overlay">
      <div class="wt-modal">
        <button type="button" class="wt-modal-close-btn">
          <svg class="wt-icon">
            <use href="${C}#icon-close-mob-menu-bt"></use>
          </svg>
        </button>
        <p class="wt-modal-tittle">${t.title.trim()}</p>
        <p class="wt-modal-message">${t.message.trim()}</p>
      </div>
    </div>
    `,{onShow:e=>{document.body.classList.add("no-scroll"),e.element().querySelector(".wt-modal-close-btn").onclick=e.close;const n=c=>{(c.key==="Escape"||c.keyCode===27)&&(e.close(),document.removeEventListener("keydown",n))};document.addEventListener("keydown",n)},onClose:()=>{document.body.classList.remove("no-scroll")}}),v=t=>{r[t.target.name]=t.target.value.trim(),localStorage.setItem("wt-form-data",JSON.stringify(r))},g=async t=>{if(t.preventDefault(),!(r.client_email===""||r.client_comment==="")){try{const{data:e}=await q(r);I(e).show()}catch(e){e instanceof h?(console.error("Axios Error:",e.message),console.error("Error Details:",e.config)):console.error(e);return}r.client_email="",r.client_comment="",localStorage.removeItem("wt-form-data"),i.reset()}},x=t=>{t.forEach(e=>{e.isIntersecting?(i.addEventListener("input",v),i.addEventListener("submit",g)):(i.removeEventListener("input",v),i.removeEventListener("submit",g))})};if(localStorage.length>0){const t=localStorage.getItem("wt-form-data");if(t){const{client_email:e,client_comment:n}=JSON.parse(t);r.client_email=e??"",r.client_comment=n??""}}i.elements.client_email.value=r.client_email;i.elements.client_comment.value=r.client_comment;const H=new IntersectionObserver(x);H.observe(i);
//# sourceMappingURL=index.js.map
